export const StringsFR = {
  introductionTexts: [
    "Bonjour, je suis Nestor, votre assistant voiturier.",
    "Scannez le QR code proposé par votre voiturier pour créer votre ticket.",
  ],
  scanQrCode: "Scanner le QR Code",
  or: "ou",
  createYourTicket: "Créer votre ticket",
  iAmValet: "Je suis voiturier",
  toCreateTicket: "pour vous créer votre ticket",
  create: "Créer",
  yourTicket: "votre Ticket 🅿️",
  qrCodeError: "Le QR code scanné est invalide.",
  retry: "Veuillez réessayer.",
  welcomeTo: "Bienvenue au",
  creationOfYourTicket: "Création de votre ticket",
  waitaFewSeconds: "Patientez quelques secondes...",
  yourTicketWithoutEmoji: "Votre Ticket",
  at: "au",
  cguTitle: "CONDITIONS GÉNÉRALES D’UTILISATION DE NESTOR APP",
  receiveByEmail: "Recevoir par email",
  problemContactUs: "Un problème ? Contactez-nous ici",
  emailTitle: "Et voilà votre ticket de voiturier 🅿️",
  invoiceDetails: "Facture",
  thanksForUsingNestor:
    "Merci d'avoir utilisé Nestor. L'application française des voituriers 🇫🇷",
  email: "EMAIL",
  invoiceDate: "DATE DE LA FACTURE",
  ticketId: "TICKET ID",
  hashtag: "#",
  place: "Lieu",
  yourReceipt: "Votre reçu",
  valetService: "Service de voiturier",
  asterisk: "*",
  problemClickHere: "Un problème ? Cliquez ici",
  euro: "€",
  total: "Total",
  seeCgu: "*Voir les conditions générales d'utilisation ci-contre:",
  copyright: "Copyright © 2024 Nestor App.",
  allRightReserved: "Tous droits réservés",
  emailLabel: "Email",
  emailPlaceholder: "nestor@gmail.com",
  enterYourEmail: "Entrez votre email",
  receiveTicket: "Recevoir le ticket",
  isSending: "Envoi...",
  emailAdressError: "Adresse mail invalide",
  emailAdressErrorDescription: "Veuillez rentrer un bon format d'adresse mail",
  emailTicketSent: "Paiement réussi!",
  emailTicketSentDescription:
    "Merci d'avoir utilisé Nestor, l'application des voituriers",
  oupsError: "Oups... Un bug a eu lieu",
  fieldError: "Erreur sur les champs",
  fieldErrorDescription: "Veuillez rentrer les bons formats de données",
  emailTicketError: "Un bug à eu lieu lors de l'envoi de votre ticket...",
  emailAuthor: "Nestor App",
  emailSubject: "Votre ticket",
  scan: "Scanner",
  qrCode: "le QR Code",
  toCreateaAccount: "pour vous créer un compte",
  toLogin: "pour vous connecter",
  createYourAccount: "Créer votre compte",
  login: "Se connecter",
  complete: "Remplissez",
  yourDetails: "vos Informations",
  name: "Prénom",
  password: "Mot de passe",
  namePlaceholder: "Samuel",
  passwordPlaceholder: "Entrer votre mot de passe",
  nameError: "Votre prénom doit faire au moins 3 caractères",
  emailError: "Vous devez rentrer un mail valide",
  passwordError: "Votre mot de passe doit contenir au moins 6 caractères",
  isRegistering: "Inscription...",
  registerErrorDescription: "Une erreur a eu lieu lors de l'inscription",
  isLoggedIn: "Connexion...",
  yourAreIn: "Vous êtes au",
  userAlreadyExist: "Un compte existe déjà avec ce mail",
  userAlreadyExistDescription:
    "Un compte voiturier existe déjà avec cette adresse mail",
  youAreIn: "Vous êtes au",
  loginErrorDescription: "Une erreur a eu lieu lors de la connexion",
  wrongMailorPassword: "Mauvaise adresse mail ou mot de passe",
  wrongMailOrPasswordDescription:
    "L'adresse mail rentrée ou le mot de passe n'est pas le bon",
  addTheImmatMissingOnTicket:
    "Vous pouvez ajouter les plaques d'immatriculations sur les tickets",
  allTicketsCompleted: "Tout vos tickets sont complétés",
  youHave: "Vous avez",
  ticket: "ticket",
  tickets: "tickets",
  toComplete: "à compléter",
  immatriculation: "Immatriculation",
  immatriculationPlaceholder: "AA-001-AA",
  createdAt: "Crée à",
  numero: "n°",
  finished: "J'ai terminé",
  deconnection: "Déconnexion...",
  immatriculationSaved: "Plaque enregistrée",
  theImmat: "La plaque",
  savedForTheTicket: "est enregistrée pour le ticket",
  aErrorOccured: "Une erreur est survenue",
  ourServerHasProblems: "Notre serveur reçoit des problèmes",
  sessionDone: "Session terminée",
  yourServiceAt: "Votre service au ",
  isFinished: " est terminé",
};
