export const StringsFR = {
  introductionTexts: [
    "Bonjour, je suis Nestor, votre assistant voiturier.",
    "Scannez le QR code proposé par votre voiturier pour créer votre ticket.",
  ],
  scanQrCode: "Scanner le QR Code",
  or: "ou",
  createYourTicket: "Créer votre ticket",
  iAmValet: "Je suis voiturier",
  toCreateTicket: "pour vous créer votre ticket",
  create: "Créer",
  yourTicket: "votre Ticket 🅿️",
  qrCodeError: "Le QR code scanné est invalide.",
  retry: "Veuillez réessayer.",
  welcomeTo: "Bienvenue au",
  creationOfYourTicket: "Création de votre ticket",
  waitaFewSeconds: "Patientez quelques secondes...",
  yourTicketWithoutEmoji: "Votre Ticket",
  at: "au",
  cguCta: "Voir les cgu",
  cguTitle: "CONDITIONS GÉNÉRALES D’UTILISATION",
  of: "DE",
  receiveByEmail: "Recevoir par email",
  problemContactUs: "Un problème ?",
  emailTitle: "Et voilà votre ticket de voiturier 🅿️",
  invoiceDetails: "Justificatif",
  thanksForUsingNestor:
    "Merci d'avoir utilisé Nestor. L'application française des voituriers 🇫🇷",
  email: "EMAIL",
  invoiceDate: "DATE DU JUSTIFICATIF",
  ticketId: "TICKET ID",
  hashtag: "#",
  place: "Lieu",
  yourReceipt: "Votre reçu",
  valetService: "Service de voiturier",
  asterisk: "*",
  problemClickHere: "Un problème ? Cliquez ici",
  euro: "€",
  total: "Total",
  seeCgu: "*Voir les conditions générales d'utilisation ci-contre:",
  copyright: "Copyright © 2024 Nestor App.",
  allRightReserved: "Tous droits réservés",
  emailLabel: "Email",
  emailPlaceholder: "nestor@gmail.com",
  enterYourEmail: "Entrez votre email",
  receiveTicket: "Recevoir le ticket",
  isSending: "Envoi...",
  emailAdressError: "Adresse mail invalide",
  emailAdressErrorDescription: "Veuillez rentrer un bon format d'adresse mail",
  emailTicketSent: "Ticket envoyé !",
  emailTicketSentDescription: "Pensez à vérifier vos spams",
  oupsError: "Oups... Un bug a eu lieu",
  fieldError: "Erreur sur les champs",
  fieldErrorDescription: "Veuillez rentrer les bons formats de données",
  emailTicketError: "Un bug à eu lieu lors de l'envoi de votre ticket...",
  emailAuthor: "Nestor App",
  emailSubject: "Votre ticket",
  scan: "Scanner",
  qrCode: "le QR Code",
  toCreateaAccount: "pour vous créer un compte",
  toLogin: "pour vous connecter",
  createYourAccount: "Créer votre compte",
  login: "Se connecter",
  complete: "Remplissez",
  yourDetails: "vos Informations",
  name: "Prénom",
  password: "Mot de passe",
  namePlaceholder: "Samuel",
  passwordPlaceholder: "Entrer votre mot de passe",
  nameError: "Votre prénom doit faire au moins 3 caractères",
  emailError: "Vous devez rentrer un mail valide",
  passwordError: "Votre mot de passe doit contenir au moins 6 caractères",
  isRegistering: "Inscription...",
  registerErrorDescription: "Une erreur a eu lieu lors de l'inscription",
  isLoggedIn: "Connexion...",
  yourAreIn: "Vous êtes au",
  userAlreadyExist: "Un compte existe déjà avec ce mail",
  userAlreadyExistDescription:
    "Un compte voiturier existe déjà avec cette adresse mail",
  youAreIn: "Vous êtes au",
  loginErrorDescription: "Une erreur a eu lieu lors de la connexion",
  wrongMailorPassword: "Mauvaise adresse mail ou mot de passe",
  wrongMailOrPasswordDescription:
    "L'adresse mail rentrée ou le mot de passe n'est pas le bon",
  wrongPhoneOrPassword: "Mauvais numéro rentré ou mot de passe",
  wrongPhoneOrPasswordDescription:
    "Le numéro de téléphone rentrée ou le mot de passe n'est pas le bon",
  addTheImmatMissingOnTicket:
    "Vous pouvez ajouter les plaques d'immatriculations sur les tickets",
  allTicketsCompleted: "Tout vos tickets sont complétés",
  youHave: "Vous avez",
  ticket: "ticket",
  tickets: "tickets",
  toComplete: "à compléter",
  immatriculation: "Immatriculation",
  immatriculationPlaceholder: "AA-001-AA",
  createdAt: "Crée à",
  numero: "n°",
  finished: "J'ai terminé",
  deconnection: "Déconnexion...",
  immatriculationSaved: "Plaque enregistrée",
  theImmat: "La plaque",
  savedForTheTicket: "est enregistrée pour le ticket",
  aErrorOccured: "Une erreur est survenue",
  ourServerHasProblems: "Notre serveur reçoit des problèmes",
  sessionDone: "Session terminée",
  yourServiceAt: "Votre service au ",
  isFinished: " est terminé",
  continueWithGoogle: "Continuer avec Google",
  showQrCode: "Montrer le QR Code",
  mayScanQrCode: "Veuillez scanner le QR Code ci-dessous:",
  areYouSureToValidateCarRetrieveTitle: "Vous avez bien rendu le véhicule ?",
  areYouSureToValidateCarRetrieveDescription: "Le ticket ne sera plus affiché",
  retrievedCar: "Véhicule rendu ?",
  cancel: "Annuler",
  ok: "Ok",
  yesGiveBackTheKey: "Oui, j’ai bien rendu le véhicule",
  titleResponsabilityModal: "Engagement voiturier",
  descriptionResponsabilityModal:
    "Je m'engage à saisir les plaques d'immatriculation et à signaler chaque départ de véhicule.",
  haveToAcceptValetRules: "Conditions requises",
  haveToAcceptValetRulesDescription: "Acceptez les conditions pour continuer.",
  acceptValetConditions: "J'ai compris et j'accepte",
  smsVerification: "Nestor : Votre code de vérification est ",
  enter: "Rentrer votre",
  yourPhoneNumber: "Téléphone",
  phoneNumber: "Numéro de téléphone",
  phoneNumberError: "Numéro invalide",
  phoneNumberErrorDescription:
    "Le format de votre numéro de téléphone est invalide",
  enterCode: "Entrer le code",
  receivedBySms: "Reçu par Sms",
  verifyYourNumber: "Vérifier votre numéro",
  verifying: "Vérification...",
  codeIsLessThan6Characters: "Le code fait moins de 6 caractères",
  codeIsLessThan6CharactersDescription:
    "Le code fourni ne respecte pas le bon format",
  phoneNumberVerificationBugError:
    "Une erreur est survenue lors de la vérification de votre numéro",
  phoneNumberVerificationError: "Mauvais code",
  VerificationErrorDescription:
    "Le code rentré ne correspond pas à celui envoyé par sms",
  codeExpiratedError: "Le code est expiré",
  codeExpiratedErrorDescription: "Veuillez renvoyer un nouveau code",
  verifyYourAccount: "Vérifier votre compte",
  weHaveSentACodeAtYourPhoneNumber: "Nous avons envoyé un code à votre numéro",
  youDidntReceivedTheCode: "Vous n'avez pas reçu le code?",
  resend: "Renvoyer",
  frenchNumberPrefix: "+33",
  // ... vos autres chaînes
  clientWaitingForCar: "Un client attend sa voiture",
  clientsWaitingForCars: "clients attendent leurs voitures",
  urgentCarPickup: "Des clients souhaitent récupérer leur véhicule.",
  clientWantToPickupHisCar: "Le client veut récupérer sa voiture",
  retrieveMyCar: "Récupérer ma voiture",
  selectTimeLabel: "Voiture prête dans...",
  selectTimePlaceholder: "Rechercher ou saisir un délai...",
  selectTimeDescription: "Sélectionnez ou saisissez le délai souhaité",
  retrieveCarModalTitle: "Récupérer ma voiture",
  sendToValet: "Envoyer au voiturier",
  retrieveCarAsked: "C'est noté !",
  retrieveCarAskedDescription: "Votre voiture sera prête à temps",
  retrieveCarError: "Erreur lors de l'envoi de la demande",
  phoneError: "Veuillez rentrer le bon format de numéro français",
  titleAddPhoneModal: "Ajoutez votre numéro",
  descriptionAddPhoneModal:
    "Renseignez votre numéro de téléphone pour recevoir les notifications des clients par SMS.",
  sendCode: "Vérifier mon numéro",
  sendingCode: "Envoi en cours...",
  phoneNumberVerified: "Numéro vérifié !",
  phoneNumberVerifiedDescription:
    "Votre numéro de téléphone a bien été vérifié",
  phoneNumberAlreadyExists: "Numéro déjà utilisé",
  phoneNumberAlreadyExistsDescription:
    "Ce numéro de téléphone est déjà associé à un autre compte",
  satisfactionModalTitle: "Merci d'avoir utilisé Nestor !",
  satisfactionQuestion:
    "Comment avez-vous trouvé votre expérience avec Nestor ?",
  satisfactionCommentLabel: "Des suggestions d'amélioration ?",
  satisfactionCommentPlaceholder:
    "Laissez-nous un commentaire/des idées d'amélioration",
  satisfactionGood: "Super",
  satisfactionBad: "J'aime pas",
  satisfactionSubmit: "Envoyer mon avis",
  satisfactionSubmitting: "Envoi...",
  satisfactionSuccess: "Merci pour votre avis !",
  satisfactionSuccessDescription: "Votre retour nous aide à améliorer Nestor",
  satisfactionError: "Erreur lors de l'envoi de votre avis",
};
