export const StringsFR = {
  introductionTexts: [
    "Bonjour, je suis Nestor, votre assistant voiturier.",
    "Scannez le QR code proposé par votre voiturier pour créer votre ticket.",
  ],
  scanQrCode: "Scanner le QR Code",
  or: "ou",
  createYourTicket: "Créer votre ticket",
  iAmValet: "Je suis voiturier",
  toCreateTicket: "pour vous créer votre ticket",
  create: "Créer",
  yourTicket: "votre Ticket 🅿️",
  qrCodeError: "Le QR code scanné est invalide.",
  retry: "Veuillez réessayer.",
  welcomeTo: "Bienvenue au",
  creationOfYourTicket: "Création de votre ticket",
  yourTicketWithoutEmoji: "Votre Ticket",
  at: "au",
  cguTitle: "CONDITIONS GÉNÉRALES D’UTILISATION DE NESTOR APP",
  receiveByEmail: "Recevoir par email",
  problemContactUs: "Un problème ? Contactez-nous ici",
  emailTitle: "Et voilà votre ticket de voiturier 🅿️",
  invoiceDetails: "Facture",
  thanksForUsingNestor:
    "Merci d'avoir utilisé Nestor. L'application française des voituriers 🇫🇷",
  email: "EMAIL",
  invoiceDate: "DATE DE LA FACTURE",
  ticketId: "TICKET ID",
  hashtag: "#",
  place: "Lieu",
  yourReceipt: "Votre reçu",
  valetService: "Service de voiturier",
  asterisk: "*",
  problemClickHere: "Un problème ? Cliquez ici",
  euro: "€",
  total: "Total",
  seeCgu: "*Voir les conditions générales d'utilisation ci-contre:",
  copyright: "Copyright © 2024 Nestor App.",
  allRightReserved: "Tous droits réservés",
  emailLabel: "Email",
  emailPlaceholder: "nestor@gmail.com",
  enterYourEmail: "Entrez votre email",
  receiveTicket: "Recevoir le ticket",
};
